<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.axa.automation.webengine</groupId>
        <artifactId>webengine-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>webengine-core</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>webengine-core</name>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>

        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
        </dependency>

        <dependency>
            <groupId>com.sun.istack</groupId>
            <artifactId>istack-commons-runtime</artifactId>
        </dependency>

    </dependencies>

    <build>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java-source.version}</source>
                    <target>${java-target.version}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.jvnet.jaxb2.maven2</groupId>
                <artifactId>maven-jaxb2-plugin</artifactId>
                <executions>
                    <execution>
                        <id>webengine-generate</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <schemaDirectory>src/main/resources/xsd/webengine</schemaDirectory>
                            <schemaIncludes>
                                <include>environnementVariables.xsd</include>
                                <include>testSuiteData.xsd</include>
                                <include>webEngineReport.xsd</include>
                            </schemaIncludes>
                            <generatePackage>fr.axa.automation.webengine.generated</generatePackage>
                            <generateDirectory>${project.build.directory}/generated-sources/webengine
                            </generateDirectory>
                            <bindingDirectory>src/main/resources/xsd/binding</bindingDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>junit-generate</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <schemaDirectory>src/main/resources/xsd/junit</schemaDirectory>
                            <schemaIncludes>
                                <include>junitTestReport.xsd</include>
                            </schemaIncludes>
                            <generatePackage>fr.axa.automation.junit.generated</generatePackage>
                            <generateDirectory>${project.build.directory}/generated-sources/junit</generateDirectory>
                            <bindingDirectory>src/main/resources/xsd/binding</bindingDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>target/generated-sources/junit</source>
                                <source>target/generated-sources/webengine</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>
