# Additional properties that will be passed to the scanner,
# Put one key=value per line, example:

sonar.projectKey=automateam.axa.webengine.java
sonar.sourceEncoding=UTF-8
sonar.projectVersion=1.0-SNAPSHOT

#sonar.exclusions=**/*.bin
#sonar.sources=./src/main
#sonar.tests=./src/test
#sonar.junit.reportsPath=target/surefire-reports
#sonar.surefire.reportsPath=target/surefire-reports
#sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco-ut/jacoco.xml
#sonar.binaries=target/classes
#sonar.java.binaries=.
#sonar.java.coveragePlugin=jacoco

sonar.modules=webengine-core,webengine-web,webengine-boot,webengine-runner

#ws-dao.sonar.sources=src
#ws-dao.sonar.coverage.exclusions=**src/test/**
#ws-dao.sonar.java.binaries=target/classes,target/generated-sources
#ws-dao.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-ut/jacoco.xml
#ws-dao.sonar.exclusions=**src/test/resources/data/**
#ws-domain.sonar.sources=src
#ws-domain.sonar.coverage.exclusions=**src/main/java/fr/axa/pfel/**
#ws-domain.sonar.java.binaries=target/classes,target/generated-sources
#ws-domain.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-ut/jacoco.xml
#ws-domain.sonar.exclusions=
#ws-service.sonar.sources=src
#ws-service.sonar.coverage.exclusions=**src/**/common/soap/**,**src/**/wspfel/soap/**,**src/**/spoolnet/soap/vo/**,**src/**/wspfel/ws/config/**,**src/test/**, **src/**/wspfel/ws/exception/**
#ws-service.sonar.java.binaries=target/classes,target/generated-sources
#ws-service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-ut/jacoco.xml
#ws-service.sonar.exclusions=

#sonar.binaries=target/classes
#sonar.java.binaries=target/classes
sonar.java.coveragePlugin=jacoco