//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 09:56:59 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.axa.fr/WebEngine/2022",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.axa.automation.webengine.jaxb.withpackageinfo;

